categories:
  - title: ":broom: Chore"
    label: "chore"
  - title: ":boom: Breaking Changes"
    label: "breaking"
  - title: ":rocket: Features"
    label: "enhancement"
  - title: ":fire: Removals and Deprecations"
    label: "removal"
  - title: ":beetle: Fixes"
    labels: ["fix", "bug"]
  - title: ":racehorse: Performance"
    label: "performance"
  - title: ":rotating_light: Testing"
    label: "testing"
  - title: ":construction_worker: Continuous Integration"
    label: "ci"
  - title: ":books: Documentation"
    label: "documentation"
  - title: ":hammer: Refactoring"
    labels:
      - "refactoring"
      - "refactor"
  - title: ":lipstick: Style"
    label: "style"
  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: "bug"
    branch:
      - "/fix\/.+/"
    title:
      - "/fix/i"
  - label: "chore"
    title:
      - "/chore/i"
  - label: "dependencies"
    title:
      - "/dependenc(y|ies)/.*/i"
    branch:
      - "/dependabot.*/"
  - label: "documentation"
    title:
      - "/documentation/i"
    files:
      - "*.md"
  - label: "refactoring"
    title:
      - "/refactor(ing)?"
