[project]
name = "homeassistant-smarter"
version = "0.1.4"
description = "Default template for PDM package"
authors = [{ name = "Kirill Birger", email = "kbirger@gmail.com" }]
dependencies = ["smarter-client==0.2.0", "homeassistant>=2024.6.0b4"]
requires-python = "~=3.12.2"
readme = "README.md"
license = { text = "MIT" }


[project.optional-dependencies]
testing = [
    "pytest-homeassistant-custom-component==0.13.128",
    "isort==5.13.2",
    "pre-commit>=3.7.0",
    "black>=24.4.2",
    "reorder-python-imports>=3.12.0",
    "flake8>=7.0.0",
    "pytest>=8.1.1",
    "pytest-cov>=5.0.0",
    "pytest-asyncio>=0.23.6",
]
[tool.pdm]
distribution = false

[tool.isort]
profile = "black"

[tool.pylint]
disable = ['no-name-in-module']

[tool.pytest.ini_options]
asyncio_mode = "auto"
pythonpath = "."
addopts = ["--allow-unix-socket"]
