[project]
name = "homeassistant-smarter"
version = "0.1.2"
description = "Default template for PDM package"
authors = [{ name = "Kirill Birger", email = "kbirger@gmail.com" }]
dependencies = [
    "smarter-client@https://github.com/kbirger/smarter-kettle-client/archive/refs/tags/v0.1.14-dev.tar.gz",
    "homeassistant>=2024.4.3",
]
requires-python = "~=3.12.2"
readme = "README.md"
license = { text = "MIT" }


[project.optional-dependencies]
testing = [
    "pytest-homeassistant-custom-component==0.13.114",
    "isort==5.13.2",
    "pre-commit>=3.7.0",
    "black>=24.4.0",
    "reorder-python-imports>=3.12.0",
    "flake8>=7.0.0",
    "pytest>=6.1.2",
]
[tool.pdm]
distribution = false

[tool.isort]
profile = "black"
