quick_boil:
  target:
    device:
      integration: smarter
    entity:
      integration: smarter
      domain: sensor

send_command:
  target:
    device:
      integration: smarter
    entity:
      integration: smarter
      domain: sensor

  fields:
    command_name:
      example: start_boil
      required: true
      selector:
        text:
    command_data_text:
      example: Foo
      required: false
      selector:
        text:
    command_data_number:
      example: 25.0
      required: false
      selector:
        number:
    command_data_boolean:
      example: True
      required: false
      selector:
        boolean:

get_commands:
  target:
    device:
      integration: smarter
    entity:
      integration: smarter
      domain: sensor
