name: Manage labels

on:
  push:
    branches:
      - main
      - master

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          skip-delete: true
