name: Linting

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
env:
  DEFAULT_PYTHON: 3.12
jobs:
    pre-commit:
        runs-on: "ubuntu-latest"
        name: Pre-commit
        steps:
          - name: Check out the repository
            uses: actions/checkout@v4.1.7

          - name: Set up Python ${{ env.DEFAULT_PYTHON }}
            uses: actions/setup-python@v5.1.1
            with:
              python-version: ${{ env.DEFAULT_PYTHON }}

          - uses: pdm-project/setup-pdm@v4
            with:
              python-version: ${{ env.DEFAULT_PYTHON }}
              cache: true
              allow-python-prereleases: true
              cache-dependency-path: |
                ./pdm.lock
                ./pdm.new.lock

          - name: Install dependencies
            run: |
              pdm venv create --with-pip --force $PYTHON
              pdm install -G linting

          - name: Run pre-commit on all files
            run: |
              pdm run pre-commit run --all-files --show-diff-on-failure --color=always
