name: Tests

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

env:
  DEFAULT_PYTHON: 3.12

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4.1.7"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4.1.7"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4.1.7"
      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        uses: "actions/setup-python@v5.2.0"
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: true
          allow-python-prereleases: true
          cache-dependency-path: |
            ./pdm.lock
            ./pdm.new.lock

      - name: Install dependencies
        run: |
          pdm venv create --with-pip --force $PYTHON
          pdm install -G testing
      - name: Tests suite
        run: |
          pdm run test-ci
