name: Linting

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"
  workflow_dispatch:

env:
  DEFAULT_PYTHON: 3.12

jobs:
  pre-commit:
    runs-on: "ubuntu-latest"
    name: Pre-commit
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5.1.0
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}

      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: true
          allow-python-prereleases: true
          cache-dependency-path: |
            ./pdm.lock
            ./pdm.new.lock

      - name: Install dependencies
        run: |
          pdm venv create --with-pip --force $PYTHON
          pdm install -G testing

      - name: Run pre-commit on all files
        run: |
          pdm run pre-commit run --all-files --show-diff-on-failure --color=always

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4.1.1"

      - name: HACS validation
        uses: "hacs/action@22.5.0"
        with:
          category: "integration"
          ignore: brands

  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: Check out the repository
        uses: "actions/checkout@v4.1.1"

      - name: Hassfest validation
        uses: "home-assistant/actions/hassfest@master"
  tests:
    runs-on: "ubuntu-latest"
    name: Run tests
    steps:
      - name: Check out code from GitHub
        uses: "actions/checkout@v4.1.1"
      - name: Setup Python ${{ env.DEFAULT_PYTHON }}
        uses: "actions/setup-python@v2.2.1"
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
          cache: true
          allow-python-prereleases: true
          cache-dependency-path: |
            ./pdm.lock
            ./pdm.new.lock

      - name: Install dependencies
        run: |
          pdm venv create --with-pip --force $PYTHON
          pdm install -G testing
      - name: Tests suite
        run: |
          pdm run pytest \
            --timeout=9 \
            --durations=10 \
            -n auto \
            -p no:sugar \
            tests
